package Common.Resources;

import java.util.ListResourceBundle;

public class Resource_ca extends ListResourceBundle {
    private static final Object[][] contents =
            {
                    {"id","ID"},
                    {"name","Nom"},
                    {"splash","Esprai"},
                    {"depth","Profun"},
                    {"color","Color"},
                    {"x","Coordenada X"},
                    {"y","Coordenada Y"},
                    {"add","Afegir element"},
                    {"remove","Eliminar element"},
                    {"removeLower","Tecla d'Esborrar menys"},
                    {"control","Control"},
                    {"import","Importar"},
                    {"save","Guardar"},
                    {"connections","Connexions"},
                    {"ip","adreça IP"},
                    {"port","Порт"},
                    {"ban","Prohibició"},
                    {"client","Client"},
                    {"server","Servidor"},
                    {"minX","Mínim X"},
                    {"maxX","Max X"},
                    {"minY","Mínim I"},
                    {"maxY","Max Y"},
                    {"minSplash","Min. esprai"},
                    {"maxSplash","Max esprai"},
                    {"minDepth","Min. profunditat"},
                    {"maxDepth","Max. profunditat"},
                    {"orange","Orange"},
                    {"blue","Blau"},
                    {"red","Vermell"},
                    {"yellow","Groc"},
                    {"start","Inici"},
                    {"stop","Stop"},
                    {"update","Actualit"},
                    {"keyExists","un element amb la mateixa clau ja existeix"},
                    {"added","Element afegit correctament"},
                    {"checkData","Objecte més Error. Consultar l'entrada"},
                    {"imported","Col·lecció importat correctament"},
                    {"fileNotFound","Fitxer no trobat"},
                    {"removedOne","Element eliminat amb èxit"},
                    {"noSuchKey","no hi ha cap element amb aquesta clau en la col·lecció"},
                    {"wrongFormat","tecla Equivocada format"},
                    {"removedMany","Elements eliminats amb èxit"},
                    {"noKeyLess","la col·lecció no té elements amb clau, menys introduir"},
                    {"saved","Col·lecció successfully saved"},
                    {"enterPath","Introduïu el camí cap a la importació de fitxer:"},
                    {"noColor","no hi ha color seleccionat"},
                    {"error","Error"},
                    {"noFilteredObjects","Cap objecte de satisfer els filtres."},
                    {"message", "Missatge"},
                    {"youUnbanned", "Que eren unban"},
                    {"youBanned", "Que han estat prohibits"},
                    {"chooseLanguage", "Выберите язык"},
                    {"language","Llengua"},
                    {"", ""},
                    {"", ""},
                    {"", ""},
                    {"", ""},
                    {"", ""},
                    {"", ""},
                    {"", ""},
                    {"", ""},

            };

    public Object[][] getContents(){return contents;}
}
