package Common.Resources;

import java.util.ListResourceBundle;

public class Resource_es_PR extends ListResourceBundle {
    private static final Object[][] contents =
            {
                    {"id","ID"},
                    {"name","Nombre"},
                    {"splash","Manchas"},
                    {"depth","Profun"},
                    {"color","Color"},
                    {"x","Coordenada X"},
                    {"y","Coordenada Y"},
                    {"add","Añadir elemento"},
                    {"remove","Eliminar elemento"},
                    {"removeLower","Eliminar con la clave de menos"},
                    {"control","Gestión"},
                    {"import","Importar"},
                    {"save","Guardar"},
                    {"connections","Conexión"},
                    {"ip","IP adress"},
                    {"port","el Puerto"},
                    {"ban","Ban"},
                    {"client","el Cliente"},
                    {"server","Servidor"},
                    {"minX","Mínimo X"},
                    {"maxX","Máximo X"},
                    {"minY","Mínimo Y"},
                    {"maxY","Máximo Y"},
                    {"minSplash","Min. manchas"},
                    {"maxSplash","Máx. manchas"},
                    {"minDepth","Min. la profundidad"},
                    {"maxDepth","Máx. la profundidad"},
                    {"orange","Naranja"},
                    {"blue","Azul"},
                    {"red","Rojo"},
                    {"yellow","Amarillo"},
                    {"start","Inicio"},
                    {"stop","Stop"},
                    {"update","Actualit"},
                    {"keyExists","Elemento\", \"con esa clave ya existe"},
                    {"added","Elemento añadido correctamente"},
                    {"checkData","Error al añadir el objeto. Compruebe los datos de entrada"},
                    {"imported","Colección se ha importado correctamente"},
                    {"fileNotFound","Archivo no encontrado"},
                    {"removedOne","el Elemento eliminado correctamente"},
                    {"noSuchKey","En la colección no hay ningún elemento de a por la llave"},
                    {"wrongFormat","formato Incorrecto de la llave"},
                    {"removedMany","Elementos eliminado con éxito"},
                    {"noKeyLess","En la colección de ningún elemento, con la llave, es menor que el valor introducido"},
                    {"saved","Colección se ha guardado correctamente"},
                    {"enterPath","Escriba la ruta de acceso al archivo de importación:"},
                    {"noColor","No se ha seleccionado un color"},
                    {"error","Ошибка"},
                    {"noFilteredObjects","No hay objetos que cumplan con los filtros"},
                    {"message", "Mensaje"},
                    {"youUnbanned", "Usted ha sido unbaneado"},
                    {"youBanned", "Has sido baneado por"},
                    {"toBan", "To ban"},
                    {"toUnban", "To unban"},
                    {"chooseLanguage", "Выберите язык"},
                    {"language","Idioma"},
                    {"", ""},
                    {"", ""},
                    {"", ""},
                    {"", ""},
                    {"", ""},
                    {"", ""},

            };

    public Object[][] getContents(){return contents;}
}
